apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: a2ov3uevs-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: a2ov3uevs-go 
  name: a2ov3uevs-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: a2ov3uevs-go 
